name: Deploy Flask App to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: echo "No tests yet"

      - name: Create zip file
        run: |
          ZIP_NAME="${{ secrets.EB_APP_NAME }}-v${{ github.run_number }}.zip"
          zip -r "$ZIP_NAME" . -x "*.git*" "*.github*"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload zip to S3
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          S3_BUCKET="elasticbeanstalk-${{ secrets.AWS_REGION }}-${ACCOUNT_ID}"
          aws s3 cp "$ZIP_NAME" s3://$S3_BUCKET/"$ZIP_NAME"

      - name: Create EB Application Version
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          S3_BUCKET="elasticbeanstalk-${{ secrets.AWS_REGION }}-${ACCOUNT_ID}"

          VERSION_LABEL="v-${{ github.run_number }}"
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket="$S3_BUCKET",S3Key="$ZIP_NAME"

      - name: Deploy to Elastic Beanstalk
        run: |
          VERSION_LABEL="v-${{ github.run_number }}"
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "$VERSION_LABEL"
